insert into sys_dict_type (id, name, code, remark, created_time, updated_time)
values
(1, 'General Status', 'sys_status', 'System general status: 1/0', now(), null),
(2, 'General Switch', 'sys_choose', 'System general switch: true/false', now(), null),
(3, 'Menu Type', 'sys_menu_type', 'System menu type', now(), null),
(4, 'Login Status', 'sys_login_status', 'User login status', now(), null),
(5, 'Data Rule Operator', 'sys_data_rule_operator', 'Data permission rule operator', now(), null),
(6, 'Data Rule Expression', 'sys_data_rule_expression', 'Data permission rule expression', now(), null),
(7, 'Frontend Config', 'sys_frontend_config', 'Frontend parameter configuration type', now(), null),
(8, 'Task Strategy Type', 'task_strategy_type', 'Scheduled task strategy type', now(), null),
(9, 'Task Period Type', 'task_period_type', 'Scheduled task period type', now(), null),
(10, 'Notice Announcement', 'notice', 'Notice type', now(), null),
(11, 'Online Status', 'user_online_status', 'User online status', now(), null),
(12, 'Plugin Type', 'sys_plugin_type', 'Plugin type', now(), null);

insert into sys_dict_data (id, type_code, label, value, color, sort, status, remark, type_id, created_time, updated_time)
values
(1, 'sys_status', 'Disabled', '0', 'red', 1, 1, 'Disabled status', 1, now(), null),
(2, 'sys_status', 'Normal', '1', 'green', 2, 1, 'Normal status', 1, now(), null),
(3, 'sys_choose', 'Off', 'false', 'error', 1, 1, 'Off status', 2, now(), null),
(4, 'sys_choose', 'On', 'true', 'success', 2, 1, 'On status', 2, now(), null),
(5, 'sys_menu_type', 'Directory', '0', 'orange', 1, 1, 'Menu directory', 3, now(), null),
(6, 'sys_menu_type', 'Menu', '1', 'default', 2, 1, 'Regular menu', 3, now(), null),
(7, 'sys_menu_type', 'Button', '2', 'processing', 3, 1, 'Menu button', 3, now(), null),
(8, 'sys_menu_type', 'Embedded', '3', 'cyan', 4, 1, 'Embedded page', 3, now(), null),
(9, 'sys_menu_type', 'External Link', '4', 'purple', 5, 1, 'External link', 3, now(), null),
(10, 'sys_login_status', 'Failed', '0', 'error', 1, 1, 'Login failed status', 4, now(), null),
(11, 'sys_login_status', 'Success', '1', 'success', 2, 1, 'Login success status', 4, now(), null),
(12, 'sys_data_rule_operator', 'AND', '0', 'green', 1, 1, 'Logical AND operator', 5, now(), null),
(13, 'sys_data_rule_operator', 'OR', '1', 'gold', 2, 1, 'Logical OR operator', 5, now(), null),
(14, 'sys_data_rule_expression', 'Equal (==)', '0', 'success', 1, 1, 'Equal comparison expression', 6, now(), null),
(15, 'sys_data_rule_expression', 'Not Equal (!=)', '1', 'error', 2, 1, 'Not equal comparison expression', 6, now(), null),
(16, 'sys_data_rule_expression', 'Greater Than (>)', '2', 'magenta', 3, 1, 'Greater than comparison expression', 6, now(), null),
(17, 'sys_data_rule_expression', 'Greater Than or Equal (>=)', '3', 'volcano', 4, 1, 'Greater than or equal comparison expression', 6, now(), null),
(18, 'sys_data_rule_expression', 'Less Than (<)', '4', 'gold', 5, 1, 'Less than comparison expression', 6, now(), null),
(19, 'sys_data_rule_expression', 'Less Than or Equal (<=)', '5', 'orange', 6, 1, 'Less than or equal comparison expression', 6, now(), null),
(20, 'sys_data_rule_expression', 'Contains (in)', '6', 'purple', 7, 1, 'Contains expression', 6, now(), null),
(21, 'sys_data_rule_expression', 'Not Contains (not in)', '7', 'error', 8, 1, 'Not contains expression', 6, now(), null),
(22, 'sys_frontend_config', 'No', '0', 'red', 1, 1, 'Not frontend parameter config', 7, now(), null),
(23, 'sys_frontend_config', 'Yes', '1', 'green', 2, 1, 'Is frontend parameter config', 7, now(), null),
(24, 'task_strategy_type', 'Interval', '0', 'cyan', 1, 1, 'Time interval strategy', 8, now(), null),
(25, 'task_strategy_type', 'Crontab', '1', 'purple', 2, 1, 'Time expression strategy', 8, now(), null),
(26, 'task_period_type', 'Days', 'days', 'processing', 1, 1, 'Scheduled task period type - days', 9, now(), null),
(27, 'task_period_type', 'Hours', 'hours', 'magenta', 2, 1, 'Scheduled task period type - hours', 9, now(), null),
(28, 'task_period_type', 'Minutes', 'minutes', 'volcano', 3, 1, 'Scheduled task period type - minutes', 9, now(), null),
(29, 'task_period_type', 'Seconds', 'seconds', 'gold', 4, 1, 'Scheduled task period type - seconds', 9, now(), null),
(30, 'task_period_type', 'Microseconds', 'microseconds', 'warning', 5, 1, 'Scheduled task period type - microseconds', 9, now(), null),
(31, 'notice', 'Notification', '0', 'magenta', 1, 1, 'Notification type', 10, now(), null),
(32, 'notice', 'Announcement', '1', 'purple', 2, 1, 'Announcement type', 10, now(), null),
(33, 'user_online_status', 'Offline', '0', 'warning', 1, 1, 'User offline status', 11, now(), null),
(34, 'user_online_status', 'Online', '1', 'success', 2, 1, 'User online status', 11, now(), null),
(35, 'sys_plugin_type', 'Archive', '0', 'gold', 1, 1, 'Plugin type - archive', 12, now(), null),
(36, 'sys_plugin_type', 'GIT', '1', 'processing', 2, 1, 'Plugin type - GIT', 12, now(), null);
